// AgendAI - Mock Data for Development (Salão de Beleza)

import { 
  Tenant, 
  Employee, 
  Service, 
  Client, 
  Appointment, 
  FinancialEntry,
  DashboardStats 
} from '@/types';

export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'Studio Beleza & Arte',
    status: 'active',
    plan: 'pro',
    createdAt: new Date('2024-01-15'),
    employeeCount: 5,
    maxEmployees: 10,
    appointmentCount: 320,
    email: 'contato@studiobeleza.com',
    phone: '11999990001',
    revenue: 45600,
  },
  {
    id: '2',
    name: 'Espaço Glamour',
    status: 'active',
    plan: 'enterprise',
    createdAt: new Date('2024-02-20'),
    employeeCount: 8,
    maxEmployees: 50,
    appointmentCount: 512,
    email: 'contato@espacoglamour.com',
    phone: '11999990002',
    revenue: 89200,
  },
  {
    id: '3',
    name: 'Bella Hair',
    status: 'inactive',
    plan: 'basic',
    createdAt: new Date('2024-03-10'),
    employeeCount: 2,
    maxEmployees: 3,
    appointmentCount: 78,
    email: 'contato@bellahair.com',
    phone: '11999990003',
    revenue: 12300,
  },
];

export const mockEmployees: Employee[] = [
  {
    id: '1',
    tenantId: '1',
    name: 'Ana Carolina',
    email: 'ana@studiobeleza.com',
    phone: '(11) 99999-0001',
    role: 'admin',
    services: ['1', '2', '3', '6'],
    workSchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isActive: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isActive: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isActive: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isActive: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '18:00', isActive: true },
      { dayOfWeek: 6, startTime: '09:00', endTime: '14:00', isActive: true },
    ],
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    tenantId: '1',
    name: 'Juliana Mendes',
    email: 'juliana@studiobeleza.com',
    phone: '(11) 99999-0002',
    role: 'employee',
    services: ['1', '2', '4'],
    workSchedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '19:00', isActive: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '19:00', isActive: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '19:00', isActive: true },
      { dayOfWeek: 4, startTime: '10:00', endTime: '19:00', isActive: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '19:00', isActive: true },
    ],
    isActive: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    tenantId: '1',
    name: 'Fernanda Costa',
    email: 'fernanda@studiobeleza.com',
    phone: '(11) 99999-0003',
    role: 'employee',
    services: ['3', '4', '5', '7'],
    workSchedule: [
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isActive: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '17:00', isActive: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isActive: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '17:00', isActive: true },
      { dayOfWeek: 6, startTime: '08:00', endTime: '12:00', isActive: true },
    ],
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
];

export const mockServices: Service[] = [
  { id: '1', tenantId: '1', name: 'Corte Feminino', description: 'Corte moderno e personalizado', duration: 45, price: 80, isActive: true },
  { id: '2', tenantId: '1', name: 'Escova', description: 'Escova modeladora profissional', duration: 40, price: 60, isActive: true },
  { id: '3', tenantId: '1', name: 'Coloração', description: 'Coloração completa com produtos premium', duration: 120, price: 180, isActive: true },
  { id: '4', tenantId: '1', name: 'Manicure', description: 'Manicure com esmaltação', duration: 45, price: 45, isActive: true },
  { id: '5', tenantId: '1', name: 'Pedicure', description: 'Pedicure completa', duration: 50, price: 55, isActive: true },
  { id: '6', tenantId: '1', name: 'Hidratação Capilar', description: 'Tratamento de hidratação profunda', duration: 60, price: 90, isActive: true },
  { id: '7', tenantId: '1', name: 'Design de Sobrancelha', description: 'Design com henna ou tintura', duration: 30, price: 40, isActive: true },
  { id: '8', tenantId: '1', name: 'Progressiva', description: 'Alisamento progressivo', duration: 180, price: 280, isActive: true },
];

export const mockClients: Client[] = [
  {
    id: '1',
    tenantId: '1',
    name: 'Maria Fernandes',
    phone: '(11) 98765-4321',
    email: 'maria@email.com',
    createdAt: new Date('2024-01-20'),
    lastVisit: new Date('2026-01-05'),
    totalAppointments: 15,
  },
  {
    id: '2',
    tenantId: '1',
    name: 'Carla Lima',
    phone: '(11) 98765-4322',
    createdAt: new Date('2024-02-15'),
    lastVisit: new Date('2026-01-04'),
    totalAppointments: 10,
  },
  {
    id: '3',
    tenantId: '1',
    name: 'Patricia Costa',
    phone: '(11) 98765-4323',
    email: 'patricia@email.com',
    createdAt: new Date('2024-03-01'),
    lastVisit: new Date('2026-01-03'),
    totalAppointments: 7,
  },
  {
    id: '4',
    tenantId: '1',
    name: 'Luciana Mendes',
    phone: '(11) 98765-4324',
    createdAt: new Date('2024-04-10'),
    lastVisit: new Date('2026-01-02'),
    totalAppointments: 4,
  },
  {
    id: '5',
    tenantId: '1',
    name: 'Beatriz Souza',
    phone: '(11) 98765-4325',
    email: 'beatriz@email.com',
    createdAt: new Date('2024-05-20'),
    totalAppointments: 2,
  },
];

const today = new Date();
const formatDate = (daysOffset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  return date;
};

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    tenantId: '1',
    clientId: '1',
    client: mockClients[0],
    employeeId: '1',
    employee: mockEmployees[0],
    serviceId: '1',
    service: mockServices[0],
    date: formatDate(0),
    startTime: '09:00',
    endTime: '09:45',
    status: 'confirmed',
    paymentStatus: 'pending',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
  {
    id: '2',
    tenantId: '1',
    clientId: '2',
    client: mockClients[1],
    employeeId: '2',
    employee: mockEmployees[1],
    serviceId: '2',
    service: mockServices[1],
    date: formatDate(0),
    startTime: '10:00',
    endTime: '10:40',
    status: 'pending',
    paymentStatus: 'pending',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
  {
    id: '3',
    tenantId: '1',
    clientId: '3',
    client: mockClients[2],
    employeeId: '1',
    employee: mockEmployees[0],
    serviceId: '6',
    service: mockServices[5],
    date: formatDate(0),
    startTime: '11:00',
    endTime: '12:00',
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: new Date(),
    createdBy: 'manual',
  },
  {
    id: '4',
    tenantId: '1',
    clientId: '4',
    client: mockClients[3],
    employeeId: '3',
    employee: mockEmployees[2],
    serviceId: '3',
    service: mockServices[2],
    date: formatDate(0),
    startTime: '14:00',
    endTime: '16:00',
    status: 'confirmed',
    paymentStatus: 'pending',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
  {
    id: '5',
    tenantId: '1',
    clientId: '5',
    client: mockClients[4],
    employeeId: '2',
    employee: mockEmployees[1],
    serviceId: '4',
    service: mockServices[3],
    date: formatDate(1),
    startTime: '09:00',
    endTime: '09:45',
    status: 'pending',
    paymentStatus: 'pending',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
  {
    id: '6',
    tenantId: '1',
    clientId: '1',
    client: mockClients[0],
    employeeId: '1',
    employee: mockEmployees[0],
    serviceId: '2',
    service: mockServices[1],
    date: formatDate(1),
    startTime: '10:30',
    endTime: '11:10',
    status: 'confirmed',
    paymentStatus: 'pending',
    createdAt: new Date(),
    createdBy: 'manual',
  },
  {
    id: '7',
    tenantId: '1',
    clientId: '2',
    client: mockClients[1],
    employeeId: '3',
    employee: mockEmployees[2],
    serviceId: '5',
    service: mockServices[4],
    date: formatDate(-1),
    startTime: '15:00',
    endTime: '15:50',
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
  {
    id: '8',
    tenantId: '1',
    clientId: '3',
    client: mockClients[2],
    employeeId: '2',
    employee: mockEmployees[1],
    serviceId: '7',
    service: mockServices[6],
    date: formatDate(-1),
    startTime: '16:00',
    endTime: '16:30',
    status: 'cancelled',
    paymentStatus: 'cancelled',
    createdAt: new Date(),
    createdBy: 'whatsapp',
  },
];

export const mockFinancialEntries: FinancialEntry[] = [
  {
    id: '1',
    tenantId: '1',
    type: 'income',
    category: 'Serviços',
    description: 'Pedicure - Carla Lima',
    amount: 55,
    date: formatDate(-1),
    appointmentId: '7',
    createdAt: new Date(),
  },
  {
    id: '2',
    tenantId: '1',
    type: 'income',
    category: 'Serviços',
    description: 'Hidratação Capilar - Patricia Costa',
    amount: 90,
    date: formatDate(0),
    appointmentId: '3',
    createdAt: new Date(),
  },
  {
    id: '3',
    tenantId: '1',
    type: 'expense',
    category: 'Materiais',
    description: 'Produtos de coloração e tratamento',
    amount: 350,
    date: formatDate(-2),
    createdAt: new Date(),
  },
  {
    id: '4',
    tenantId: '1',
    type: 'expense',
    category: 'Aluguel',
    description: 'Aluguel do espaço',
    amount: 3500,
    date: formatDate(-5),
    createdAt: new Date(),
  },
  {
    id: '5',
    tenantId: '1',
    type: 'income',
    category: 'Produtos',
    description: 'Venda de shampoo e condicionador',
    amount: 120,
    date: formatDate(-3),
    createdAt: new Date(),
  },
];

export const mockDashboardStats: DashboardStats = {
  todayAppointments: 4,
  pendingAppointments: 2,
  completedToday: 1,
  todayRevenue: 90,
  weeklyRevenue: 1250,
  monthlyRevenue: 4800,
  topServices: [
    { name: 'Corte Feminino', count: 52 },
    { name: 'Escova', count: 45 },
    { name: 'Manicure', count: 38 },
    { name: 'Coloração', count: 25 },
  ],
  appointmentsByStatus: [
    { status: 'completed', count: 186 },
    { status: 'confirmed', count: 28 },
    { status: 'pending', count: 12 },
    { status: 'cancelled', count: 8 },
  ],
};
