project_id = "pyqkcfgkwdisabklrxfl"

[functions.lead-broadcast]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.client-lookup]
verify_jwt = false

[functions.available-professionals]
verify_jwt = false

[functions.client-identify]
verify_jwt = false

[functions.services]
verify_jwt = false

[functions.establishment-info]
verify_jwt = false

[functions.create-appointment]
verify_jwt = false

[functions.reschedule-appointment]
verify_jwt = false

[functions.cancel-appointment]
verify_jwt = false