project_id = "pyqkcfgkwdisabklrxfl"

[functions.lead-broadcast]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.client-lookup]
verify_jwt = false